apiVersion: v1
kind: Namespace
metadata:
  name: ferrishost

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ferrishost-web
  namespace: ferrishost

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ferrishost-web
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ferrishost-web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ferrishost-web
subjects:
  - kind: ServiceAccount
    name: ferrishost-web
    namespace: ferrishost
